version: "3.8"

services:
  csvserver:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9393"
    volumes:
      - ./inputFile:/csvserver/inputFile
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

